apiVersion: apps/v1
kind: Deployment
metadata:
  name: citesting-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: citesting-app

  template:
    metadata:
      labels:
        app: citesting-app

    spec:
      containers:
        - name: citesting-container
          image: aashish1717/testing:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ci