name: CI Pipeline - CI Testing



on:
  push:
    branches: ["master"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Build and Run Tests with Maven
        run: mvn clean verify -Dspring.profiles.active=ci


      - name: Get App Version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/docker-demo-project:${{ env.APP_VERSION }} .


      - name: Push to Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-demo-project:${{ env.APP_VERSION }}